### ISSUE TITLE
Demo video title update required !

### ISSUE THREAD

**Issue by zzkatz** [BurhanRaja/iNotebook_Frontend#1]
Currently the demo title for the project is ` bandicam.2022-07-01.19-35-50-954.mp4 `

Problems with this are
1. Doesn't specify the use case.
2. Shares unwanted information.

## Suggestion
Project Demo

**Comment by BurhanRaja** [comment]
Is it ok now?

**Comment by BurhanRaja** [comment]
Thank you so much for the help. It means a lot. Let's collaborate in future too.

**Comment by zzkatz** [comment]
Please change the name for video source file
